name: notez
description: Aplikasi pemantauan akademik dan aktivitas santri
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  get: ^4.6.5
  sqflite: ^2.3.0
  flutter_launcher_icons: ^0.14.3
  intl: ^0.18.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

# Konfigurasi flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_app.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logo_app.jpg"
